### ISSUE TITLE
Compatibility with The Forge Cloudhosting

### ISSUE THREAD

**Issue by jerichojx** [YourFavouriteOreo/VTT-Chat-Reactions#10]
Recently I have been using the Forge Cloudhosting and the Custom Emoji's folder cannot be created on the module level as The Forge handles that separately.
I tried to load custom emoji's as an asset but while I can choose the emoji in the picker, after choosing the emoji, I get a broken file icon.
![Chat reactions 2](https://user-images.githubusercontent.com/67579273/123606962-a2b49580-d827-11eb-9258-7cde129ec6fb.png)
![Chatreactions 1](https://user-images.githubusercontent.com/67579273/123606972-a47e5900-d827-11eb-861d-1a95922d5cdf.png)

**Comment by YourFavouriteOreo** [comment]
Hmm, i've never used forge cloudhosting but also the custom emoji folder doesnt have to be at module level. Any chance  I could get access ur foundry?
