### ISSUE TITLE
[BUG] I can't react to messages with Custom Emotes

### ISSUE THREAD

**Issue by brunocalado** [YourFavouriteOreo/VTT-Chat-Reactions#11]
I added a custom image to chat reactions. I can use this image if a send through the chat: ex.: myimage.png :myimage:

But, when I react I got an error:
![image](https://user-images.githubusercontent.com/4999783/124133808-94998b80-da58-11eb-990d-cdf054830b36.png)

![image](https://user-images.githubusercontent.com/4999783/124133834-9bc09980-da58-11eb-87a7-5dcd67019c00.png)

Config:
![image](https://user-images.githubusercontent.com/4999783/124133896-aa0eb580-da58-11eb-9f33-e55b613f0ef1.png)

**Comment by YourFavouriteOreo** [comment]
what is the exact name of the image?

**Comment by brunocalado** [comment]
mdemote.png

**Comment by Asinphi** [comment]
Custom emojis should work in the latest releases.
