### ISSUE TITLE
Unable to update the module

### ISSUE THREAD

**Issue by happy-cujo** [YourFavouriteOreo/VTT-Chat-Reactions#12]
## Configuration
- Foundry VTT 0.8.8

## Steps to reproduce
1. Install module via in-app module manager
2. Try to update it

## Expected
Module is updated successfully

## Actual
![image](https://user-images.githubusercontent.com/15898113/127142254-f444d85d-cb7b-4f7e-8c36-0974b12e9ec2.png)

## Notes
I need to remove the module completely and install it again via in-app module manager in order to get the most recent version.
The [link](https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/releases/download/lastest/dist/module.json) from the error message returns 404 not found error.

**Comment by sharkbruhaha** [comment]
can confirm

**Comment by crogonint** [comment]
Same behavior on 0.8.9
It says that it 'did not provide a valid manifest file.'
