### ISSUE TITLE
Does not work anymore for me on v10

### ISSUE THREAD

**Issue by Myriade91** [YourFavouriteOreo/VTT-Chat-Reactions#16]
Suddenly this morning i could not click anymore on configure settings on foundry with that module installed. When i removed it i wanted to reinstall it and it is unavailable. Seems it's no more compatible with latest version. Can you fix it?

**Comment by YourFavouriteOreo** [comment]
V10 compatibility has been implemented by @Asinphi and added for foundry today. Should be all good
