### ISSUE TITLE
Error with fp2e game system saving throw buttons

### ISSUE THREAD

**Issue by SatiricalBard** [YourFavouriteOreo/VTT-Chat-Reactions#17]
Hi, I have found a possible bug with Chat Reactions 2.2.0 on PF2 Game System 4.6.8 on Foundry 10.291: it seems to be breaking the saving throw button links in chat cards. 

I can push-to-chat the buttons from the character sheet, but nothing happens when the player clicks the button, nor for me as game master. I also can't push-to-chat from another card in the chat (eg. the card describing the effect triggering the saving throw). This is true even with Chat Reactions (and sockelib) as the only modules activated. Deactivating Chat Reactions fixes the issue. 

![screenshot](https://user-images.githubusercontent.com/122022095/215360916-7d2bd8b2-3fc9-4740-a83c-292ad22ef195.png)

Screenshot of the kind of 'saving throw button' I'm talking about. Normally in the pf2e system if you put one of these in the chat, players can click on the button to auto-roll the relevant saving throw, with the roll compared to the set DC and the results announced in a chat card. 

Happy to chat via discord if you want to troubleshoot - juswhe#8234

**Comment by Asinphi** [comment]
I couldn't reproduce the issue using the latest version of PF2 Game System, so updating the system may solve it.
