### ISSUE TITLE
V9 Player Compatibility 

### ISSUE THREAD

**Issue by GeneralKilljoy** [YourFavouriteOreo/VTT-Chat-Reactions#18]
After attempting to use ChatReactions 1.4.0 on FVTT v 9.280 it works for the DM but not players. The players can add to emoji the DM has reacted with but no menu/options appear when clicking the "+" to add a new reaction or emoji to a chat message. 

Is this expected do to no v9 specific release or is it something wrong on my end

**Comment by Asinphi** [comment]
This might be because of an issue that broke the old emoji picker from the old v9 release. The issue was fixed in the newer releases, but unfortunately, the v9 releases won't be getting further updates.
