### ISSUE TITLE
Bug with Midi QoL Module

### ISSUE THREAD

**Issue by bernardovento** [YourFavouriteOreo/VTT-Chat-Reactions#19]
Hi, the module have a bug with midi-QoL
Bug:
![MIdi QOL Reaction](https://user-images.githubusercontent.com/40549558/224079705-619600f4-8b31-42c6-bf88-654c38355685.png)
Normal:
![Midi Qol Normal](https://user-images.githubusercontent.com/40549558/224079731-b1110baa-64e8-4ff0-8430-4283d6ada93a.png)

**Comment by igotsmeakabob11** [comment]
I've had the same issue. It causes similar issues in some other modules as well, for instance TheRipper's new D&D5e System customization module.

**Comment by Shayulghul** [comment]
Same issue here. It's definitely a CSS conflict. I think I isolated it to the following:
<section class=“window-content”>
.window-app . window-content
{display: flex;}

If you turn off the flex, all other windows work properly but the emoji popout doesn't render. You get a message, "Failed to load emojis. Try again."

**Comment by Asinphi** [comment]
Fixed with the 2.3.0 release
