### ISSUE TITLE
Is it possible to post the emotes in chat?

### ISSUE THREAD

**Issue by LiveLaden** [YourFavouriteOreo/VTT-Chat-Reactions#2]
Instead of just having a reaction bar, is it also possible to post the emotes in chat, it's something that I've been trying to find for a while.

Also, creating a shortcut of an image gives a broken image, don't know if that is intended

**Comment by YourFavouriteOreo** [comment]
Currently that's not built in functionality but I could add that to the list . 

However there are these alternatives for emojis in chat
https://www.foundryvtt-hub.com/package/emojule/
https://www.foundryvtt-hub.com/package/emojimancy/

What do you mean by creating a shortcut of an image?

**Comment by LiveLaden** [comment]
I have some emotes on my F:/Emotes for example, on my HDD, and instead of copying them to my Foundry folder, I tried just creating a shortcut of them, to see if it would work, but it gives a broken image, probably expected

**Comment by YourFavouriteOreo** [comment]
Oh yeah that's definitely expected behaviour. If u want to avoid copying the folder over. You could technically create a symbolic link to your emoji folder and that should work but I haven't tested that.

**Comment by YourFavouriteOreo** [comment]
![emojis_unlocked](https://user-images.githubusercontent.com/10431292/119935771-14839000-bf99-11eb-8a60-8d541f057d32.gif)

@LiveLaden  the feature u requested should be out with the next version

**Comment by LiveLaden** [comment]
Holy shit, thanks so much. Amazing stuff 👍

**Comment by YourFavouriteOreo** [comment]
Update 1.3.0 is out . Enjoy!
