### ISSUE TITLE
When you attempt to update the module in v11 it gives an error

### ISSUE THREAD

**Issue by Zamrod** [YourFavouriteOreo/VTT-Chat-Reactions#22]
I get the following error whenever I check for updates on the module:

Error: No module manifest found at https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/releases/latest/download/dist/module.json

**Comment by YourFavouriteOreo** [comment]
https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/releases/download/v2.3.0/module.json should work , try it

**Comment by Zamrod** [comment]
That works but after you install it, every time you hit the update button it tries to download the update from the wrong place so it throws the error.

**Comment by Asinphi** [comment]
Fixed! I tracked down the bug's cause to Github automated actions replacing the manifest URL with the one in the error. After downloading version 2.3.3 from the URL https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/releases/download/v2.3.3/module.json (or uninstalling and reinstalling), there should be no more issues checking for updates!
