### ISSUE TITLE
Module suddenly nonfunctional

### ISSUE THREAD

**Issue by weepingminotaur** [YourFavouriteOreo/VTT-Chat-Reactions#23]
Screenshots attached. I'm running Chrome on Mac Version 115.0.5790.98, Foundry v11, Pf2e 5.1.2, macOS Venture 13.4.1
<img width="554" alt="Screenshot 2023-07-19 at 9 16 03 AM" src="https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/assets/90105219/a3aaab11-e95f-4c92-94cc-96d988d50adc">
<img width="485" alt="Screenshot 2023-07-19 at 9 16 18 AM" src="https://github.com/YourFavouriteOreo/VTT-Chat-Reactions/assets/90105219/48493186-9ac4-4c59-be4d-d66e5585fea4">

**Comment by Asinphi** [comment]
This issue *should* be fixed in the 2.3.4 release. I haven't been able to replicate it, but I tracked down the apparent cause to the emoji picker library and implemented the solution.

**Comment by weepingminotaur** [comment]
Yep, just updated and tested and it works fine now! Thank you.
