### ISSUE TITLE
FPS Drop/Stutter Opening then Closing Configure Settings

### ISSUE THREAD

**Issue by FreshnessDND** [YourFavouriteOreo/VTT-Chat-Reactions#24]
Foundry v11.306
DnD5e v2.2.2

No other modules enabled.

Chat Reactions enabled.

1. Open configure settings.
2. Close configure settings.
3. FPS Drops/Stutters browsing canvas.
4. Open configure settings
5. FPS Drops/Stutters gone.
6. Close configure settings
7. FPS Drops/Stutters return.

No errors or warnings. No addition of modification of the module helped.

**Comment by Asinphi** [comment]
I'm unable to replicate the issue, but it might just be that I have better hardware. I also can't imagine that there's anything in the code that could be causing this. Do you also experience this issue with no modules enabled at all?
Some bug fixes were done with the game canvas in Foundry build 307, so check if updating fixes your issue.
