### ISSUE TITLE
Getting this error when trying to update

### ISSUE THREAD

**Issue by LiveLaden** [YourFavouriteOreo/VTT-Chat-Reactions#3]
![image](https://user-images.githubusercontent.com/33188462/120243945-44ec5800-c23f-11eb-8ac8-b4896b9dc679.png)

Still stuck on 1.2.1

**Comment by YourFavouriteOreo** [comment]
ah crap, uninstall the component then reinstall from foundryvtt

**Comment by LiveLaden** [comment]
![image](https://user-images.githubusercontent.com/33188462/120342930-a60f3c80-c2ce-11eb-8cad-f8a9a9d6da07.png)
Weird, it reinstalls the 1.2.1 version, I will try to manually install, now
I even made sure it got deleted in the Modules folder

**Comment by LiveLaden** [comment]
![image](https://user-images.githubusercontent.com/33188462/120343327-fe463e80-c2ce-11eb-82c6-6a6eadccb5bb.png)
Manually installed, still giving me 1.2.1 version

**Comment by YourFavouriteOreo** [comment]
Oh , wait, 
I forgot the update for 0.8.6 was recentl,, let me do some changes and get back to you

**Comment by YourFavouriteOreo** [comment]
Can you try it now ?

If it doesnt work please add me on discord and we can try figuring it out YourFavouriteOreo#6798

**Comment by YourFavouriteOreo** [comment]
Issue was solved in DMs
