### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by VoltCruelerz** [YourFavouriteOreo/VTT-Chat-Reactions#4]
After installing, when pressing `Check Update` on the module manager tab of Foundry, this error comes up:

![image](https://user-images.githubusercontent.com/4068550/120794290-00dea900-c506-11eb-9679-c92841a3d078.png)

**Comment by YourFavouriteOreo** [comment]
Heyo, this bug can be fixed by manually uninstalling and reinstalling the module . I messed up when packaging it . It'll install 1.3 but call it 1.2.1 , still figuring out the best way to fix it 🙏🏼
