### ISSUE TITLE
Please make sure a scene is loaded before reacting to messages

### ISSUE THREAD

**Issue by Fyrexian** [YourFavouriteOreo/VTT-Chat-Reactions#6]
As a DM, I am able to react to messages. However, my players are unable to react getting "Please make sure a scene is loaded before reacting to messages" at all times.

**Comment by YourFavouriteOreo** [comment]
Heyo, what version of chat reactions and is there a scene loaded?

**Comment by Fyrexian** [comment]
Core version is .7.1   
Chat Reactions is at 1.2.1  
Dnd 5E (1.2.4) 

And I'm assuming , "scene is loaded" means that when the background picture is visible and activated. Because it is then.
![image](https://user-images.githubusercontent.com/47077661/120933914-d9344000-c6c1-11eb-8c34-8d66e8b4a331.png)

**Comment by YourFavouriteOreo** [comment]
Firstly please try updating your chat reactions version to 1.3.0

If that doesnt fix it :
Is there any error in console ? 
To enter the console press F12 then click on the console tab . Chat Reactions is only rated for 0.7.9+ but hopefully it will still be compatibly with 0.7.1

**Comment by Fyrexian** [comment]
Didn't realize I had to update by downloading the foundry installation again, so I thought I was on the most stable version. It works now, thanks for the help
