### ISSUE TITLE
Non-Reaction Emojis rendering at a different size

### ISSUE THREAD

**Issue by oamsden** [YourFavouriteOreo/VTT-Chat-Reactions#7]
This is a new feature request, or a slight modification to an existing feature.  Currently emoji can be used not only as reactions, but as the content of a chat message themselves.  When an emoji is used in this context, it should be rendered larger to improve visibility.  They currently render in at the same size as if they were used in a reaction.  

Thoughts on how to determine size:
- Size of original image.
- Size equal to the width of the chat window (scaled while maintaining aspect ratio)
- Scaled to a maximum size as determined by a setting

Original Image:
![partywizard](https://user-images.githubusercontent.com/7940000/121076019-e4f83300-c7a3-11eb-980c-e5a4f8fd7cd1.gif)

Size comparison in chat window:
![image](https://user-images.githubusercontent.com/7940000/121075346-13294300-c7a3-11eb-8ca3-addbaf591fe0.png)

**Comment by YourFavouriteOreo** [comment]
![emoji-big](https://user-images.githubusercontent.com/10431292/121114875-647a1680-c825-11eb-9670-682c996fb7ad.PNG)
This is coming with the next update

**Comment by YourFavouriteOreo** [comment]
This feature released with 1.4.0 , customization should be on route with the next version.
