### ISSUE TITLE
Non-Visible Actors in Combat Tracker Disappear

### ISSUE THREAD

**Issue by oamsden** [YourFavouriteOreo/VTT-Chat-Reactions#8]
With the Chat Reactions module active, an actor that has had it's visibility toggled, either from the combat tracker, or from the token itself, disappears from the combat tracker.  All modules are disabled other than Chat Reactions and socketlib, and this bug is reproducible. 

![image](https://user-images.githubusercontent.com/7940000/121604088-e7fb5980-ca17-11eb-9119-7bf98826f4ab.png)

**Comment by YourFavouriteOreo** [comment]
Hmm, thats weird , ill take  a look at it

**Comment by YourFavouriteOreo** [comment]
@oamsden  unless I accidentally fixed it with my current update , it doesn't perform this bug . I'll try rushing out this patch so you can test it out.
![bug_resport](https://user-images.githubusercontent.com/10431292/121625905-72c66d80-ca85-11eb-9dd0-3c529bfe59f0.gif)

**Comment by YourFavouriteOreo** [comment]
@oamsden  deployed and available . Please see if version 1.4.0 fixes ur issue

**Comment by YourFavouriteOreo** [comment]
Going to assume this fixed your issue. Please reopen if it didnt
