### ISSUE TITLE
updating in 0.8x causes error

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [YourFavouriteOreo/VTT-Chat-Reactions#9]
updating in 0.8x i receive this message: 

"the request to This is auto replaced did not provide a valid manifest file"

just thought you should know.

**Comment by YourFavouriteOreo** [comment]
What is ur current chat reactions version

**Comment by ThingsCouldGetDicey** [comment]
1.2.1

**Comment by YourFavouriteOreo** [comment]
Please try uninstalling the module and reinstalling

**Comment by ThingsCouldGetDicey** [comment]
thats fixed it. it wasnt redirecting properly.

**Comment by YourFavouriteOreo** [comment]
I messed up on original setup and fixed it along the way as it was my first module 😅  Glad you are enjoying the module
